name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write      # for OIDC
      contents: read       # to fetch your code

    steps:
      # 1. Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Node.js 18.x
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Bake in your production API URL and build
      - name: Build application
        run: |
          echo "REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }}" > .env.production
          npm run build

      # 5. Deploy the `build/` folder
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: upload
          app_location: "/"         # The folder with your package.json
          skip_app_build: true      # We already ran `npm run build`
          output_location: "build"  # CRA’s output dir
